server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 951103
  application:
    name: service-provider
mybatis:
  type-aliases-package: cqupt.service.pojo
eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
